import { describe, expect, it } from 'vitest';
import { convertToEquipment, convertToEquipmentDTO } from '../equipment';
import { Equipment, EquipmentDTO } from '@/models/equipment';

describe('equipment convertions', () => {
  describe('to equipment', () => {
    const testCases: { name: string; value: Partial<EquipmentDTO>; expected: Partial<Equipment> }[] = [
      {
        name: 'handles a "common data" convertion',
        value: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
        },
        expected: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
        },
      },
      {
        name: 'converts the full equipment data',
        value: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchase_date: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          license_plate_number: 'I<3DST',
          insurance_carrier: 'Contructors Insurance',
          insurance_policy_number: '8849950-29934',
          insurance_contact_name: 'Bob',
          insurance_contact_phone_number: '555-930-2994',
          insurance_contact_email: 'bob@conins.com',
          equipment_type_rid: 4,
          equipment_types: {
            id: 4,
            name: 'Intergallactic Space Cruiser',
            description: 'A large, wasteful space craft.',
          },
          todo_collections: [
            {
              id: 1,
              name: 'Daily Chores',
              description: 'Tasks to complete every day.',
              due_date: null,
              is_complete: false,
              event_rid: null,
              equipment_rid: 42,
              todo_items: [
                {
                  id: 1,
                  name: 'Wash Dishes',
                  is_complete: false,
                  todo_collection_rid: 1,
                },
                {
                  id: 2,
                  name: 'Make Bed',
                  is_complete: true,
                  todo_collection_rid: 1,
                },
                {
                  id: 3,
                  name: 'Do Laundry',
                  is_complete: false,
                  todo_collection_rid: 1,
                },
              ],
            },
            {
              id: 2,
              name: 'Work Tasks',
              description: 'Tasks to accomplish during office hours.',
              due_date: null,
              is_complete: false,
              event_rid: null,
              equipment_rid: 42,
              todo_items: [
                {
                  id: 1,
                  name: 'Email Clients',
                  is_complete: false,
                  todo_collection_rid: 2,
                },
                {
                  id: 2,
                  name: 'Prepare Presentation',
                  is_complete: false,
                  todo_collection_rid: 2,
                },
                {
                  id: 3,
                  name: 'Attend Meetings',
                  is_complete: true,
                  todo_collection_rid: 2,
                },
                {
                  id: 4,
                  name: 'Submit Report',
                  is_complete: false,
                  todo_collection_rid: 2,
                },
              ],
            },
            {
              id: 3,
              created_at: new Date().toISOString(),
              name: 'Fitness Goals',
              description: null,
              due_date: '2023-12-31',
              is_complete: false,
              event_rid: null,
              equipment_rid: 42,
              todo_items: [
                {
                  id: 1,
                  name: 'Run 5k',
                  is_complete: false,
                  todo_collection_rid: 3,
                },
                {
                  id: 2,
                  name: 'Workout at Gym',
                  is_complete: false,
                  todo_collection_rid: 3,
                },
              ],
            },
          ],
          equipment_events: [
            {
              id: 1,
              name: 'Spring Inspection',
              description: 'Generally in good condition.',
              equipment_rid: 42,
              date: '2025-05-20',
              usage: null,
              cost: null,
              equipment_event_type_rid: 5,
              equipment_event_types: {
                id: 5,
                name: 'Condition Report',
                description:
                  'Inspect the equipment and provide a report of its current condition based on this assessment.',
              },
              usage_units_rid: null,
            },
            {
              id: 2,
              name: '2025 Fall Oil Change',
              equipment_rid: 42,
              date: '2025-08-15',
              usage: 12834.3,
              cost: 123.43,
              equipment_event_type_rid: 2,
              equipment_event_types: {
                id: 2,
                name: 'Periodic Maintenance',
                description: 'Periodic change of oil and other fluids. May also include related periodic maintenance.',
              },
              usage_units_rid: 1,
              usage_units: { id: 1, name: 'Miles' },
            },
            {
              id: 3,
              name: 'Spring Inspection',
              description: 'The brakes squeak a bit, but it does not seem to be a problem overall.',
              equipment_rid: 42,
              date: '2025-03-17',
              usage: 12.7,
              cost: null,
              equipment_event_type_rid: 2,
              equipment_event_types: {
                id: 2,
                name: 'Periodic Maintenance',
                description: 'Periodic change of oil and other fluids. May also include related periodic maintenance.',
              },
              usage_units_rid: 2,
              usage_units: { id: 2, name: 'Hours' },
            },
          ],
        },
        expected: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchaseDate: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          licensePlateNumber: 'I<3DST',
          insuranceCarrier: 'Contructors Insurance',
          insurancePolicyNumber: '8849950-29934',
          insuranceContactName: 'Bob',
          insuranceContactPhoneNumber: '555-930-2994',
          insuranceContactEmail: 'bob@conins.com',
          equipmentType: {
            id: 4,
            name: 'Intergallactic Space Cruiser',
            description: 'A large, wasteful space craft.',
          },
          equipmentEvents: [
            {
              id: 1,
              name: 'Spring Inspection',
              description: 'Generally in good condition.',
              equipmentRid: 42,
              date: '2025-05-20',
              usage: null,
              cost: null,
              equipmentEventType: {
                id: 5,
                name: 'Condition Report',
                description:
                  'Inspect the equipment and provide a report of its current condition based on this assessment.',
              },
            },
            {
              id: 2,
              name: '2025 Fall Oil Change',
              equipmentRid: 42,
              date: '2025-08-15',
              usage: 12834.3,
              cost: 123.43,
              equipmentEventType: {
                id: 2,
                name: 'Periodic Maintenance',
                description: 'Periodic change of oil and other fluids. May also include related periodic maintenance.',
              },
              usageUnits: { id: 1, name: 'Miles' },
            },
            {
              id: 3,
              name: 'Spring Inspection',
              description: 'The brakes squeak a bit, but it does not seem to be a problem overall.',
              equipmentRid: 42,
              date: '2025-03-17',
              usage: 12.7,
              cost: null,
              equipmentEventType: {
                id: 2,
                name: 'Periodic Maintenance',
                description: 'Periodic change of oil and other fluids. May also include related periodic maintenance.',
              },
              usageUnits: { id: 2, name: 'Hours' },
            },
          ],
          todoCollections: [
            {
              id: 1,
              name: 'Daily Chores',
              description: 'Tasks to complete every day.',
              dueDate: null,
              isComplete: false,
              eventRid: null,
              equipmentRid: 42,
              todoItems: [
                {
                  id: 1,
                  name: 'Wash Dishes',
                  isComplete: false,
                  todoCollectionRid: 1,
                },
                {
                  id: 2,
                  name: 'Make Bed',
                  isComplete: true,
                  todoCollectionRid: 1,
                },
                {
                  id: 3,
                  name: 'Do Laundry',
                  isComplete: false,
                  todoCollectionRid: 1,
                },
              ],
            },
            {
              id: 2,
              name: 'Work Tasks',
              description: 'Tasks to accomplish during office hours.',
              dueDate: null,
              isComplete: false,
              eventRid: null,
              equipmentRid: 42,
              todoItems: [
                {
                  id: 1,
                  name: 'Email Clients',
                  isComplete: false,
                  todoCollectionRid: 2,
                },
                {
                  id: 2,
                  name: 'Prepare Presentation',
                  isComplete: false,
                  todoCollectionRid: 2,
                },
                {
                  id: 3,
                  name: 'Attend Meetings',
                  isComplete: true,
                  todoCollectionRid: 2,
                },
                {
                  id: 4,
                  name: 'Submit Report',
                  isComplete: false,
                  todoCollectionRid: 2,
                },
              ],
            },
            {
              id: 3,
              name: 'Fitness Goals',
              description: null,
              dueDate: '2023-12-31',
              isComplete: false,
              eventRid: null,
              equipmentRid: 42,
              todoItems: [
                {
                  id: 1,
                  name: 'Run 5k',
                  isComplete: false,
                  todoCollectionRid: 3,
                },
                {
                  id: 2,
                  name: 'Workout at Gym',
                  isComplete: false,
                  todoCollectionRid: 3,
                },
              ],
            },
          ],
        },
      },
      {
        name: 'converts the full equipment data without child collections',
        value: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchase_date: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          license_plate_number: 'I<3DST',
          insurance_carrier: 'Contructors Insurance',
          insurance_policy_number: '8849950-29934',
          insurance_contact_name: 'Bob',
          insurance_contact_phone_number: '555-930-2994',
          insurance_contact_email: 'bob@conins.com',
          equipment_type_rid: 4,
          equipment_types: {
            id: 4,
            name: 'Intergallactic Space Cruiser',
            description: 'A large, wasteful space craft.',
          },
        },
        expected: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchaseDate: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          licensePlateNumber: 'I<3DST',
          insuranceCarrier: 'Contructors Insurance',
          insurancePolicyNumber: '8849950-29934',
          insuranceContactName: 'Bob',
          insuranceContactPhoneNumber: '555-930-2994',
          insuranceContactEmail: 'bob@conins.com',
          equipmentType: {
            id: 4,
            name: 'Intergallactic Space Cruiser',
            description: 'A large, wasteful space craft.',
          },
        },
      },
      {
        name: 'converts the full equipment data w/o joins',
        value: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchase_date: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          license_plate_number: 'I<3DST',
          insurance_carrier: 'Contructors Insurance',
          insurance_policy_number: '8849950-29934',
          insurance_contact_name: 'Bob',
          insurance_contact_phone_number: '555-930-2994',
          insurance_contact_email: 'bob@conins.com',
          equipment_type_rid: 4,
        },
        expected: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchaseDate: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          licensePlateNumber: 'I<3DST',
          insuranceCarrier: 'Contructors Insurance',
          insurancePolicyNumber: '8849950-29934',
          insuranceContactName: 'Bob',
          insuranceContactPhoneNumber: '555-930-2994',
          insuranceContactEmail: 'bob@conins.com',
        },
      },
    ];

    it.each(testCases)('$name', ({ value, expected }) => {
      expect(convertToEquipment(value)).toEqual(expected);
    });
  });

  describe('to DTO', () => {
    const testCases: { name: string; value: Equipment; expected: EquipmentDTO }[] = [
      {
        name: 'converts a full Equipment for CRUD',
        value: {
          id: 42,
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchaseDate: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          licensePlateNumber: 'I<3DST',
          insuranceCarrier: 'Contructors Insurance',
          insurancePolicyNumber: '8849950-29934',
          insuranceContactName: 'Bob',
          insuranceContactPhoneNumber: '555-930-2994',
          insuranceContactEmail: 'bob@conins.com',
          equipmentType: {
            id: 4,
            name: 'Intergallactic Space Cruiser',
            description: 'A large, wasteful space craft.',
          },
        },
        expected: {
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchase_date: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          license_plate_number: 'I<3DST',
          insurance_carrier: 'Contructors Insurance',
          insurance_policy_number: '8849950-29934',
          insurance_contact_name: 'Bob',
          insurance_contact_phone_number: '555-930-2994',
          insurance_contact_email: 'bob@conins.com',
          equipment_type_rid: 4,
        },
      },
      {
        name: 'trims the strings',
        value: {
          id: 42,
          name: '    Planet Destroyer ',
          description: ' The Vogons should destroy the Earth using this.   ',
          purchaseDate: '   2025-03-28 ',
          cost: 2954932.34,
          manufacturer: '   Vogon Vehicles ',
          model: ' DST-X3 ',
          identification: ' 1994-ff8ge-1234',
          length: '   7 Miles, 4 feet ',
          weight: '1.1 Million Tons (Roughly)    ',
          capacity: 'A full crew ',
          licensePlateNumber: ' I<3DST    ',
          insuranceCarrier: ' Contructors Insurance  ',
          insurancePolicyNumber: '  8849950-29934 ',
          insuranceContactName: '  Bob ',
          insuranceContactPhoneNumber: '  555-930-2994    ',
          insuranceContactEmail: '  bob@conins.com ',
          equipmentType: {
            id: 4,
            name: 'Intergallactic Space Cruiser',
            description: 'A large, wasteful space craft.',
          },
        },
        expected: {
          name: 'Planet Destroyer',
          description: 'The Vogons should destroy the Earth using this.',
          purchase_date: '2025-03-28',
          cost: 2954932.34,
          manufacturer: 'Vogon Vehicles',
          model: 'DST-X3',
          identification: '1994-ff8ge-1234',
          length: '7 Miles, 4 feet',
          weight: '1.1 Million Tons (Roughly)',
          capacity: 'A full crew',
          license_plate_number: 'I<3DST',
          insurance_carrier: 'Contructors Insurance',
          insurance_policy_number: '8849950-29934',
          insurance_contact_name: 'Bob',
          insurance_contact_phone_number: '555-930-2994',
          insurance_contact_email: 'bob@conins.com',
          equipment_type_rid: 4,
        },
      },
      {
        name: 'sets unspecified values to null',
        value: {
          id: 42,
          name: 'Planet Destroyer',
          equipmentType: {
            id: 4,
            name: 'Intergallactic Space Cruiser',
            description: 'A large, wasteful space craft.',
          },
          description: '',
          purchaseDate: '',
          cost: null,
          manufacturer: '',
          model: '',
          identification: '',
          length: '',
          weight: '',
          capacity: '',
          licensePlateNumber: '',
          insuranceCarrier: '',
          insurancePolicyNumber: '',
          insuranceContactName: '',
          insuranceContactPhoneNumber: '',
          insuranceContactEmail: '',
        },
        expected: {
          name: 'Planet Destroyer',
          equipment_type_rid: 4,
          description: null,
          purchase_date: null,
          cost: null,
          manufacturer: null,
          model: null,
          identification: null,
          length: null,
          weight: null,
          capacity: null,
          license_plate_number: null,
          insurance_carrier: null,
          insurance_policy_number: null,
          insurance_contact_name: null,
          insurance_contact_phone_number: null,
          insurance_contact_email: null,
        },
      },
    ];

    it.each(testCases)('$name', ({ value, expected }) => {
      expect(convertToEquipmentDTO(value)).toEqual(expected);
    });
  });
});
